"""Sprite sheets (generated by tools/build_assets.mjs) and the skin catalogue."""

from dataclasses import dataclass
from functools import lru_cache

import pygame

from .config import ASSETS, INK

IMAGES = ASSETS / "images"
DIRECTIONS = ("right", "down", "left", "up")  # sheet row order


@dataclass(frozen=True)
class Skin:
    key: str
    label: str
    cost: tuple[tuple[int, int], ...] = ()  # (fruit index, count)


SKINS = (
    Skin("classic", "CLASSIC"),
    Skin("neon", "NEON", ((0, 12), (1, 5))),
    Skin("robot", "ROBOT", ((2, 12), (3, 5))),
    Skin("ninja", "NINJA", ((3, 12), (4, 5))),
    Skin("astro", "ASTRO", ((4, 12), (5, 5))),
    Skin("slime", "SLIME", ((5, 12), (6, 5))),
    Skin("gold", "GOLD", ((5, 15), (6, 15))),
)
SKIN_BY_KEY = {s.key: s for s in SKINS}
GHOST_NAMES = ("blinky", "pinky", "inky", "clyde")


@lru_cache(maxsize=None)
def image(path: str) -> pygame.Surface:
    return pygame.image.load(str(IMAGES / path)).convert_alpha()


def frames(path: str, w: int, h: int) -> list[pygame.Surface]:
    """Slice a one-row sheet into frames."""
    sheet = image(path)
    return [sheet.subsurface((i * w, 0, w, h)) for i in range(sheet.get_width() // w)]


def directional(path: str, w: int, h: int) -> dict[str, list[pygame.Surface]]:
    """Slice a sheet whose rows are right/down/left/up."""
    sheet = image(path)
    return {
        d: [sheet.subsurface((i * w, row * h, w, h)) for i in range(sheet.get_width() // w)]
        for row, d in enumerate(DIRECTIONS)
    }


@lru_cache(maxsize=None)
def pacman_art(skin: str):
    return {
        "walk": directional(f"pacman/{skin}/walk.png", 13, 13),
        "dead": frames(f"pacman/{skin}/dead.png", 15, 15),
        "aura": image(f"pacman/{skin}/aura.png"),
    }


@lru_cache(maxsize=None)
def ghost_art(name: str):
    return {"walk": directional(f"ghost/{name}/walk.png", 14, 14), "aura": image(f"ghost/{name}/aura.png")}


@lru_cache(maxsize=None)
def shared_art():
    return {
        "eyes": directional("ghost/eaten.png", 12, 12),
        "scared": frames("ghost/frightened_1.png", 14, 14),
        "flash": frames("ghost/frightened_2.png", 14, 14),
        "fruits": frames("other/fruits.png", 12, 12),
        "medals": frames("other/medals.png", 16, 16),
    }


def maze_image(level_name: str, tint) -> pygame.Surface:
    """The level's neon glow layer tinted to `tint` on the ink background."""
    layer = image(f"maze/{level_name}.png")
    out = pygame.Surface(layer.get_size(), 0, 24)
    out.fill(INK)
    tinted = layer.copy()
    tinted.fill((*tint, 255), special_flags=pygame.BLEND_RGBA_MULT)
    out.blit(tinted, (0, 0))
    return out
